language: python
matrix:
    include:
        - python: "2.7"
          env: NUMPY_VERSION=1.11
        - python: "2.7"
          env: NUMPY_VERSION=1.12
        - python: "2.7"
          env: NUMPY_VERSION=1.13
        - python: "2.7"
          env: NUMPY_VERSION=1.14
        - python: "2.7"
          env: NUMPY_VERSION=1.15
        - python: "2.7"
          env: NUMPY_VERSION=1.16
        - python: "pypy"
          env: NUMPY_VERSION=1.11
        - python: "pypy"
          env: NUMPY_VERSION=1.12
        - python: "pypy"
          env: NUMPY_VERSION=1.13
        - python: "pypy"
          env: NUMPY_VERSION=1.14
        - python: "pypy"
          env: NUMPY_VERSION=1.15
        - python: "pypy"
          env: NUMPY_VERSION=1.16
        - python: "3.4"
          env: NUMPY_VERSION=1.11 PIL_VERSION=5.4
        - python: "3.4"
          env: NUMPY_VERSION=1.12 PIL_VERSION=5.4
        - python: "3.4"
          env: NUMPY_VERSION=1.13 PIL_VERSION=5.4
        - python: "3.4"
          env: NUMPY_VERSION=1.14 PIL_VERSION=5.4
        - python: "3.4"
          env: NUMPY_VERSION=1.15 PIL_VERSION=5.4
        - python: "3.4"
          env: NUMPY_VERSION=1.16 PIL_VERSION=5.4
        - python: "3.5"
          env: NUMPY_VERSION=1.12
        - python: "3.5"
          env: NUMPY_VERSION=1.13
        - python: "3.5"
          env: NUMPY_VERSION=1.14
        - python: "3.5"
          env: NUMPY_VERSION=1.15
        - python: "3.5"
          env: NUMPY_VERSION=1.16
        - python: "3.6"
          env: NUMPY_VERSION=1.12
        - python: "3.6"
          env: NUMPY_VERSION=1.13
        - python: "3.6"
          env: NUMPY_VERSION=1.14
        - python: "3.6"
          env: NUMPY_VERSION=1.15
        - python: "3.6"
          env: NUMPY_VERSION=1.16
        - python: "3.6"
          env: NUMPY_VERSION=1.17
        - python: "3.7"
          env: NUMPY_VERSION=1.15
        - python: "3.7"
          env: NUMPY_VERSION=1.16
        - python: "3.7"
          env: NUMPY_VERSION=1.17
        - python: "pypy3"
          env: NUMPY_VERSION=1.12
        - python: "pypy3"
          env: NUMPY_VERSION=1.13
        - python: "pypy3"
          env: NUMPY_VERSION=1.14
        - python: "pypy3"
          env: NUMPY_VERSION=1.15
        - python: "pypy3"
          env: NUMPY_VERSION=1.16
        - python: "pypy3"
          env: NUMPY_VERSION=1.17
    allow_failures:
        # Broken Numpy 1.16 build in Travis' pypy3 tarball
        - python: "pypy3"
          env: NUMPY_VERSION=1.16
install:
    - travis_retry pip install "numpy==${NUMPY_VERSION}.*"
    - if [[ -n "${PIL_VERSION}" ]]; then travis_retry pip install "pillow==${PIL_VERSION}.*"; fi
    - travis_retry pip install -e .[test]
script: make test
before_install:
    - pip install codecov
after_success:
    - codecov
